import Footer from '@/components/Footer';
import Header from '@/components/Header/index';
import './globals.css'; // make sure Tailwind/global styles are loaded

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
